spring.application.name=monitoring-dashboard

server.port=${PORT:8080}

spring.jpa.hibernate.ddl-auto=update

spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
